### ISSUE TITLE
SIGSEGV in xmpp_component example with Prosody

### ISSUE THREAD

**Issue by bodqhrohro** [FluuxIO/go-xmpp#126]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x4e28fa]

goroutine 1 [running]:
encoding/xml.(*Decoder).Token(0x0, 0x0, 0x0, 0xc000016140, 0xc0000f3968)
	/usr/lib/go-1.13/src/encoding/xml/xml.go:282 +0x3a
gosrc.io/xmpp/stanza.NextStart(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9512e0, 0x709820)
	/media/d/temp/git/go-xmpp/stanza/parser.go:79 +0x67
gosrc.io/xmpp/stanza.NextPacket(0x0, 0xc0000ec000, 0x71cff9, 0x19, 0xc0000f3aa8)
	/media/d/temp/git/go-xmpp/stanza/parser.go:53 +0x40
gosrc.io/xmpp.(*Component).Resume(0xc000087520, 0x0, 0x0, 0x0, 0xc000082d40, 0x10)
	/media/d/temp/git/go-xmpp/component.go:92 +0x4a0
gosrc.io/xmpp.(*StreamManager).resume(0xc000085200, 0x0, 0x0, 0x0, 0x40dca8, 0x30)
	/media/d/temp/git/go-xmpp/stream_manager.go:127 +0x108
gosrc.io/xmpp.(*StreamManager).connect(...)
	/media/d/temp/git/go-xmpp/stream_manager.go:115
gosrc.io/xmpp.(*StreamManager).Run(0xc000085200, 0xc000085200, 0x1)
	/media/d/temp/git/go-xmpp/stream_manager.go:97 +0xba
main.main()
	/media/d/temp/git/go-xmpp/_examples/xmpp_component/xmpp_component.go:47 +0x4de
```

According to Wireshark, the crash happens right after a successful handshake.

This is a regression, as it worked well in 0.1.3, before the introduction of Transport abstraction.

**Comment by mremond** [comment]
I confirm the issue, I committed a fix for a related issue, but it is still not a fix for that crash after handshake.
